### ISSUE TITLE
difference between pvc size and snapshot size

### ISSUE THREAD

**Issue by fragolinux** [ryaneorth/k8s-scheduled-volume-snapshotter#21]
hi, i've some issues using latest (0.12.2 updated yesterday from previous 0.10.4, now i just saw you released 0.12.3 in latest hours)

i have some PVCs of 10gb on both lab and qa NS
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/21192010/217791456-cd60ae6f-11f4-4d1e-86e0-7725fb9803bf.png">

but as you can see, the VS of the lab ones (in green, on top) have a restoresize of 100gb, so wrong... the QA ns one seems correct, though, and the snapshotter is the same for both envs...

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/21192010/217791964-c1d90b41-8a82-42bd-a854-b365cacfcb05.png">

if you need any other info, just ask

best regards, and thanks

**Comment by ryaneorth** [comment]
I'm not sure how this would really have anything to do with the scheduled volume snapshotter, as all it does is create snapshot objects and let's the CSI driver handle the rest. If you provision a snapshot manually (not using the scheduled volume snapshotter) do you experience the same behavior?

**Comment by fragolinux** [comment]
you're right, done some snapshots manually and they have the same issues (10x times bigger), it' not related to the scheduler, which as you say just asks the csi driver to do them... sorry, we can close this
