### ISSUE TITLE
add options to avoid queue and just wait for next schedule time

### ISSUE THREAD

**Issue by fragolinux** [ryaneorth/k8s-scheduled-volume-snapshotter#22]
hi, is it possible to add [this](https://stackoverflow.com/questions/52691631/kubernetes-cronjob-skip-job-if-previous-is-still-running-and-wait-for-the-next) kind of behaviour?

to give you a context of the problem, we had issues on azure, which has a limit of 200 snapshot per file share, as something was broken they reached a top of above 700, so i had to remove them manually.

but after i cleaned everything, all the missed snapshots started to be enqueued to be executed, and this just does not make sense: i don't need 20 daily snapshots all for the SAME day, if one is missed, just wait for next round...

as per the article above, it seems we need 2 values, `concurrencyPolicy` and `startingDeadlineSeconds`:

set the following property to Forbid in CronJob yaml (this is already done in chart template, i just checked)

`.spec.concurrencyPolicy`
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy

`spec.concurrencyPolicy: Forbid` will hold off starting a second job if there is still an old one running. However that job will be queued to start immediately after the old job finishes.

To skip running a new job entirely and instead wait until the next scheduled time, set .spec.startingDeadlineSeconds to be smaller than the cronjob interval (but larger than the max expected startup time of the job).

If you're running a job every 30 minutes and know the job will never take more than one minute to start, set `.spec.startingDeadlineSeconds: 60`

thanks

**Comment by ryaneorth** [comment]
Great suggestion! I've incorporated this in a new release: [v0.13.0](https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/releases/tag/v0.13.0)
