### ISSUE TITLE
Truncation for schedule volume snapshot label in child VolumeSnapshot object

### ISSUE THREAD

**Issue by bsgrigorov** [ryaneorth/k8s-scheduled-volume-snapshotter#25]
When the schedule volume snapshot object is used to create a VolumeSnapshot, it uses its name as one of the labels. Labels can be max 63 chars, but object names can be longer.

Thus creation of the VolumeSnapshot would fail. We need to truncate the scheduled-volume-snapshot name when used in the label of VolumeSnapshot: 
https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/blob/main/snapshotter.py#L90

**Comment by ryaneorth** [comment]
Thanks for reporting this issue @bsgrigorov! Fixed in the latest release: [v0.14.1](https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/releases/tag/v0.14.1)
