### ISSUE TITLE
support for arm64

### ISSUE THREAD

**Issue by portos060474** [ryaneorth/k8s-scheduled-volume-snapshotter#28]
Hi, 
Can you add support for arm64 arhitecture (arm64v8/python)?
```
─$ k logs  scheduled-volume-snapshotter-28626525-4v95b -n default
exec /usr/local/bin/python: exec format error
```

**Comment by ryaneorth** [comment]
Hey @portos060474 - I've attempted to build an alternative image using amd64, but unfortunately do not have a Kubernetes cluster with amd64 nodes at my disposal. I've pushed the image up to docker hub. If possible could you please test it by installing the helm chart using this alternative image?

The image is `ryaneorth/scheduled-volume-snapshotter:arm64` and can be specified by setting the [`.image.tag` Helm argument of `arm64`](https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/blob/main/helm/charts/scheduled-volume-snapshotter/values.yaml#L7).

If your testing shows that things work as you'd expect I'll work on updating the repository to automatically create this version of the image when releasing new versions.

**Comment by portos060474** [comment]
It's working fine. Thanks! I was trying to build and use it locally, but had some issues accessing local registry (microk8s)

**Comment by ryaneorth** [comment]
Images now support both amd64 and arm64 architectures when new releases are published. Release [v0.16.0](https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/releases/tag/v0.16.0) is the first release to support this. I'm going to delete the `arm64` tag I pushed up to test later this week so I recommend switching over to this latest release. If you encounter any problems, let me know!
